import { ASSISTANT_ROUTE_IDS, SETUP_STEP_IDS, type AssistantRouteId } from './contracts';

const routeContent: Readonly<Record<AssistantRouteId, string>> = {
  setup: `
    <div class="route-heading"><p class="eyebrow" data-i18n="setupEyebrow"></p><h2 id="route-setup-title" tabindex="-1" data-i18n="setupTitle"></h2><p data-i18n="setupIntro"></p></div>
    <div class="setup-progress" aria-labelledby="setup-progress-label"><div class="progress-copy"><span id="setup-progress-label" data-i18n="setupProgress"></span><output id="setup-progress-value"></output></div><progress id="setup-progress" max="7" value="0"></progress></div>
    <ol class="setup-steps">${SETUP_STEP_IDS.map((step, index) => setupStep(step, String(index + 1))).join('')}</ol>
    ${setupStage('microphone', 'One', 'conversation', 'setupChooseMicrophone')}
    ${setupStage('soniox', 'Two', 'providers', 'setupConfigureSoniox')}
    ${setupStage('transcription', 'Three', 'home', 'setupConfigureTranscription')}
    ${setupStage('speech', 'Four', 'voice', 'setupConfigureSpeech')}
    ${setupStage('provider', 'Five', 'providers', 'setupConfigureProvider')}
    ${setupStage('agent', 'Six', 'agents', 'setupConfigureAgent')}
    ${setupStage('rehearsal', 'Seven')}
    <div class="setup-actions"><button class="secondary" id="setup-cancel" type="button" data-setup-cancel data-i18n="setupCancel"></button></div>`,
  home: `
    <div class="route-heading"><p class="eyebrow" data-i18n="homeEyebrow"></p><h2 id="route-home-title" tabindex="-1" data-i18n="homeTitle"></h2><p data-i18n="homeIntro"></p></div>
    <section aria-labelledby="readiness-heading"><div class="section-heading"><h3 id="readiness-heading" data-i18n="readinessTitle"></h3><p data-i18n="readinessHelp"></p></div><div class="readiness-grid">${readinessCard('transcription', 'providers')}${readinessCard('microphone', 'conversation')}${readinessCard('reasoning', 'providers')}${readinessCard('speech', 'voice')}${readinessCard('actions', 'actions')}${readinessCard('privacy', 'privacy')}</div></section>
    <section class="surface" aria-labelledby="preferences-heading"><div class="section-heading"><h3 id="preferences-heading" data-i18n="preferencesTitle"></h3><p data-i18n="preferencesHelp"></p></div><div class="form-grid">
      <div class="field"><label for="ui-language" data-i18n="uiLanguage"></label><select id="ui-language"><option value="en" data-i18n="uiEnglish"></option><option value="he" data-i18n="uiHebrew"></option></select><p class="help" data-i18n="uiLanguageHelp"></p><div class="override" id="override-uiLanguage" hidden></div></div>
      <div class="field"><label for="language-hint" data-i18n="transcriptionLanguage"></label><select id="language-hint"></select><p class="help" data-i18n="transcriptionLanguageHelp"></p><div class="override" id="override-languageHint" hidden></div></div>
      <div class="field"><label for="history-ttl" data-i18n="historyRetention"></label><select id="history-ttl"><option value="0" data-i18n="forever"></option><option value="1" data-i18n="oneDay"></option><option value="7" data-i18n="sevenDays"></option><option value="30" data-i18n="thirtyDays"></option></select><p class="help" data-i18n="historyRetentionHelp"></p><div class="override" id="override-historyTtlDays" hidden></div></div>
      <div class="field"><label for="injection-mode" data-i18n="insertionMode"></label><select id="injection-mode"><option value="auto" data-i18n="injectionAuto"></option><option value="paste-key" data-i18n="injectionPaste"></option><option value="type-key" data-i18n="injectionType"></option><option value="editor-only" data-i18n="injectionEditor"></option><option value="clipboard-only" data-i18n="injectionClipboard"></option></select><p class="help" data-i18n="insertionModeHelp"></p><div class="override" id="override-injectionMode" hidden></div></div>
    </div><div class="inline-actions"><div><span class="field-label" data-i18n="shortcut"></span><code class="command-id" id="shortcut-default" dir="ltr"></code><p class="help" data-i18n="shortcutHelp"></p></div><div class="button-row"><button class="secondary" id="open-keybindings" type="button" data-i18n="openKeyboardShortcuts"></button><button class="link-button" id="open-native-settings" type="button" data-i18n="openNativeSettings"></button></div></div></section>`,
  conversation: `
    <div class="route-heading"><p class="eyebrow" data-i18n="conversationEyebrow"></p><h2 id="route-conversation-title" tabindex="-1" data-i18n="conversationTitle"></h2><p data-i18n="conversationIntro"></p></div>
    <section class="surface" aria-labelledby="conversation-session-heading"><div class="section-heading"><h3 id="conversation-session-heading" data-i18n="conversationSessionTitle"></h3><p data-i18n="assistantNeverAutoStarts"></p></div><div class="status-row"><span id="assistant-status"></span><button id="assistant-action" type="button"></button></div></section>
    <section class="surface" aria-labelledby="conversation-microphone-heading"><div class="section-heading"><h3 id="conversation-microphone-heading" data-i18n="microphoneTitle"></h3><p data-i18n="microphoneSummary"></p></div><div class="field"><label for="microphone-device" data-i18n="microphoneDevice"></label><select id="microphone-device"></select><div class="override" id="override-audioDevice" hidden></div></div><div class="button-row"><button id="microphone-scan" type="button" data-i18n="microphoneScan"></button><button class="secondary" id="microphone-guide-button" type="button" aria-expanded="false" aria-controls="microphone-guide" data-i18n="microphoneGuideButton"></button></div><p class="inline-status" id="microphone-status"></p><div class="callout" id="microphone-guide" role="note" hidden><p data-i18n="microphoneGuide"></p></div></section>`,
  agents: `
    <div class="route-heading"><p class="eyebrow" data-i18n="agentsEyebrow"></p><h2 id="route-agents-title" tabindex="-1" data-i18n="agentsTitle"></h2><p data-i18n="agentsIntro"></p></div>
    <section class="surface" aria-labelledby="listening-settings-heading"><div class="section-heading"><h3 id="listening-settings-heading" data-i18n="wakePhrase"></h3><p data-i18n="wakePhraseHelp"></p></div><div class="field"><label for="assistant-wake-phrase" data-i18n="wakePhrase"></label><input id="assistant-wake-phrase" type="text" maxlength="256" autocomplete="off" spellcheck="false" dir="auto" data-i18n-placeholder="wakePhrasePlaceholder" /><div class="override" id="override-assistantWakePhrase" hidden></div></div><div class="consent-row"><span id="assistant-consent-status"></span><button class="secondary" id="assistant-consent-action" type="button"></button></div></section>
    <section class="surface" aria-labelledby="agent-create-heading"><div class="section-heading"><h3 id="agent-create-heading" data-i18n="agentCreate"></h3><p data-i18n="agentInstructionsHostOnly"></p></div><div class="inline-actions"><div class="field"><label for="agent-template" data-i18n="agentTemplate"></label><select id="agent-template"><option value="teacher-lecturer" data-i18n="personaTeacher"></option><option value="secretary" data-i18n="personaSecretary"></option><option value="friend" data-i18n="personaFriend"></option><option value="tour-guide" data-i18n="personaGuide"></option><option value="mathematician" data-i18n="personaMathematician"></option><option value="philosopher" data-i18n="personaPhilosopher"></option></select></div><button id="agent-create" type="button" data-i18n="agentCreate"></button></div></section>
    <div id="agent-list" class="agent-list"></div>`,
  providers: `
    <div class="route-heading"><p class="eyebrow" data-i18n="providersEyebrow"></p><h2 id="route-providers-title" tabindex="-1" data-i18n="providersRouteTitle"></h2><p data-i18n="providersRouteIntro"></p></div>
    <h3 id="pipeline-title" class="sr-only" data-i18n="pipelineTitle"></h3><ol class="service-pipeline compact" aria-labelledby="pipeline-title"><li><strong>Soniox</strong><span data-i18n="pipelineTranscription"></span></li><li><strong data-i18n="pipelineReasoningTitle"></strong><span data-i18n="pipelineReasoning"></span></li><li><strong data-i18n="pipelineSpeechTitle"></strong><span data-i18n="pipelineSpeech"></span></li></ol>
    <article class="provider-card" data-provider="soniox"><div class="card-heading"><div><p class="eyebrow" data-i18n="providerRoleStt"></p><h3 data-i18n="sonioxTitle"></h3></div><span class="status-badge" id="soniox-readiness"></span></div><p class="help" data-i18n="sonioxHelp"></p><div class="field"><label for="stt-model" data-i18n="transcriptionModel"></label><select id="stt-model"></select><p class="help" data-i18n="transcriptionModelHelp"></p><div class="override" id="override-sttModel" hidden></div></div><p class="inline-status" id="metadata-status"></p>${providerActions('soniox')}</article>
    <section class="surface" aria-labelledby="provider-selection-heading"><div class="section-heading"><h3 id="provider-selection-heading" data-i18n="assistantProvider"></h3><p data-i18n="assistantProviderHelp"></p></div><div class="field"><label for="assistant-provider" data-i18n="assistantProvider"></label><select id="assistant-provider"></select></div></section>
    <div id="provider-list" class="provider-list"></div>`,
  voice: `
    <div class="route-heading"><p class="eyebrow" data-i18n="voiceEyebrow"></p><h2 id="route-voice-title" tabindex="-1" data-i18n="voiceTitle"></h2><p data-i18n="voiceIntro"></p></div>
    <section class="surface"><div class="card-heading"><div><p class="eyebrow" data-i18n="providerRoleTts"></p><h3 data-i18n="systemSpeechTitle"></h3></div><span class="status-badge" id="system-tts-readiness"></span></div><label class="check-row" for="speech-enabled"><input id="speech-enabled" type="checkbox" /><span data-i18n="speechEnabled"></span></label><p class="help" data-i18n="speechEnabledHelp"></p><div class="override" id="override-assistantSpeechEnabled" hidden></div><div class="form-grid"><div class="field"><label for="speech-voice" data-i18n="speechVoice"></label><select id="speech-voice"></select><div class="override" id="override-assistantSpeechVoiceUri" hidden></div></div><div class="field"><label for="speech-rate"><span data-i18n="speechRate"></span>: <output id="speech-rate-value"></output></label><input id="speech-rate" type="range" min="0.5" max="2" step="0.1" /><div class="override" id="override-assistantSpeechRate" hidden></div></div></div><div class="field"><label for="speech-test-phrase" data-i18n="speechTestPhrase"></label><input id="speech-test-phrase" type="text" maxlength="1000" autocomplete="off" dir="auto" data-i18n-placeholder="speechTestPlaceholder" /></div><div class="button-row"><button id="speech-test" type="button" data-i18n="speechTest"></button><button class="secondary" id="speech-stop" type="button" data-i18n="speechStop"></button></div><p class="inline-status" id="speech-status"></p></section>`,
  actions: `
    <div class="route-heading"><p class="eyebrow" data-i18n="actionsEyebrow"></p><h2 id="route-actions-title" tabindex="-1" data-i18n="actionsTitle"></h2><p data-i18n="actionsIntro"></p></div><aside class="callout approval-callout" role="note"><h3 data-i18n="approvalTransparencyTitle"></h3><p data-i18n="approvalTransparencyBody"></p></aside><section class="surface" aria-labelledby="approval-context-heading"><div class="section-heading"><h3 id="approval-context-heading" data-i18n="approvalContextTitle"></h3></div><dl class="identity-list" id="approval-context"><div><dt data-i18n="approvalActiveAgent"></dt><dd id="approval-active-agent" dir="auto"></dd></div><div><dt data-i18n="approvalActiveProvider"></dt><dd id="approval-active-provider" dir="ltr"></dd></div><div><dt data-i18n="approvalActiveModel"></dt><dd id="approval-active-model" dir="ltr"></dd></div><div><dt data-i18n="approvalPermissionTier"></dt><dd id="approval-permission-tier"></dd></div></dl></section><section class="surface" aria-labelledby="saved-actions-heading"><div class="section-heading"><h3 id="saved-actions-heading" data-i18n="savedActionsTitle"></h3><p data-i18n="mappingsHelp"></p></div><button id="mapping-add" type="button" data-i18n="mappingAdd"></button><p class="inline-status" id="mappings-status"></p><div class="mapping-list" id="mapping-list"></div></section><section class="surface" aria-labelledby="approval-history-heading"><h3 id="approval-history-heading" data-i18n="approvalHistoryTitle"></h3><div id="approval-history" class="approval-history"></div></section>`,
  privacy: `
    <div class="route-heading"><p class="eyebrow" data-i18n="privacyEyebrow"></p><h2 id="route-privacy-title" tabindex="-1" data-i18n="privacyRouteTitle"></h2><p data-i18n="privacyRouteIntro"></p></div><div class="trust-card"><strong id="workspace-trust-status"></strong><p class="help" data-i18n="workspaceTrustHelp"></p></div><div class="flow-list"><article><p class="eyebrow" data-i18n="providerRoleStt"></p><h3 data-i18n="sonioxTitle"></h3><p data-i18n="sonioxPrivacy"></p></article><article><p class="eyebrow" data-i18n="providerRoleReasoning"></p><h3 data-i18n="providersRouteTitle"></h3><p data-i18n="providerPrivacySummary"></p></article><article><p class="eyebrow" data-i18n="providerRoleTts"></p><h3 data-i18n="localTitle"></h3><p data-i18n="localPrivacy"></p></article></div><div class="consent-row"><span id="privacy-assistant-consent"></span><button class="secondary" type="button" data-consent="assistant-listening"></button></div><div id="provider-privacy-list" class="provider-privacy-list"></div><section class="surface" aria-labelledby="override-heading"><h3 id="override-heading" data-i18n="overrideHeading"></h3><div id="workspace-overrides"></div></section>`,
  diagnostics: `
    <div class="route-heading"><p class="eyebrow" data-i18n="diagnosticsEyebrow"></p><h2 id="route-diagnostics-title" tabindex="-1" data-i18n="diagnosticsRouteTitle"></h2><p data-i18n="diagnosticsRouteIntro"></p></div><section class="surface"><p class="help" data-i18n="diagnosticsHelp"></p><dl class="diagnostics-meta"><div><dt data-i18n="version"></dt><dd id="diagnostics-version" dir="ltr"></dd></div><div><dt data-i18n="platform"></dt><dd id="diagnostics-platform" dir="ltr"></dd></div></dl><div class="button-row"><button type="button" data-diagnostics="run" data-i18n="diagnosticsRun"></button><button class="secondary" type="button" data-diagnostics="open" data-i18n="diagnosticsOpen"></button><button class="secondary" type="button" data-diagnostics="copy" data-i18n="diagnosticsCopy"></button></div><p class="inline-status" id="diagnostics-status"></p><div id="diagnostics-checks" class="check-list"></div></section>`,
};

/** Stable shell: route changes and host updates never replace the root. */
export function renderSettingsShell(): string {
  return `<a class="skip-link" href="#settings-main" data-i18n="skipToSettings"></a><header class="page-header"><div><p class="eyebrow" data-i18n="productEyebrow"></p><h1 data-i18n="pageTitle"></h1><p data-i18n="pageIntro"></p></div><div id="settings-live" class="live-status" role="status" aria-live="polite" aria-atomic="true"></div></header><div class="app-layout"><nav class="route-nav" aria-labelledby="product-navigation-title"><h2 id="product-navigation-title" data-i18n="navigationTitle"></h2><div class="route-list">${ASSISTANT_ROUTE_IDS.map(renderRouteButton).join('')}</div></nav><main id="settings-main" tabindex="-1">${ASSISTANT_ROUTE_IDS.map(renderRoute).join('')}</main></div>`;
}

function renderRouteButton(id: AssistantRouteId): string {
  return `<button class="route-link" type="button" data-route="${id}" aria-controls="route-${id}"><span data-i18n="route${capitalized(id)}"></span><span class="route-marker" aria-hidden="true"></span></button>`;
}

function renderRoute(id: AssistantRouteId): string {
  return `<section class="route-panel" id="route-${id}" data-route-panel="${id}" aria-labelledby="route-${id}-title" ${id === 'setup' ? '' : 'hidden'}>${routeContent[id]}</section>`;
}

function setupStep(id: string, number: string): string {
  return `<li><button class="setup-step" type="button" data-setup-step="${id}" aria-controls="setup-${id}-title"><span class="step-number" aria-hidden="true">${number}</span><span data-i18n="setup${capitalized(id)}Short"></span><span class="step-state" id="setup-step-state-${id}"></span></button></li>`;
}

function setupStage(
  id: string,
  number: string,
  route?: AssistantRouteId,
  configureKey?: string,
): string {
  const configure = route && configureKey
    ? `<button class="secondary" type="button" data-route="${route}" data-i18n="${configureKey}"></button>`
    : '';
  return `<div class="setup-stage" data-setup-panel="${id}" aria-labelledby="setup-${id}-title" hidden><p class="eyebrow" data-i18n="setupStep${number}"></p><h3 id="setup-${id}-title" data-i18n="setup${capitalized(id)}Title"></h3><p data-i18n="setup${capitalized(id)}Body"></p><p class="readiness-line" id="setup-status-${id}" role="status"></p><div class="button-row"><button type="button" data-setup-run="${id}" data-i18n="setupRunCheck"></button>${configure}</div></div>`;
}

function readinessCard(id: string, route: AssistantRouteId): string {
  return `<article class="readiness-card" data-readiness-card="${id}"><div><h4 data-i18n="readiness${capitalized(id)}Title"></h4><p data-i18n="readiness${capitalized(id)}Help"></p></div><div class="readiness-footer"><span class="status-badge" id="readiness-${id}"></span><button class="link-button" type="button" data-route="${route}" data-i18n="readinessOpen"></button></div></article>`;
}

function providerActions(id: 'soniox' | 'deepseek'): string {
  return `<p class="credential-status" id="${id}-credential-status" tabindex="-1"></p><p class="help" data-i18n="credentialNativeOnly"></p><div class="button-row provider-actions" data-provider="${id}"><button type="button" data-credential-action="set" data-i18n="credentialSet"></button><button type="button" data-credential-action="replace" data-i18n="credentialReplace"></button><button class="secondary" type="button" data-test-action="start" data-i18n="credentialTest"></button><button class="secondary" type="button" data-test-action="cancel" data-i18n="credentialCancelTest"></button><button class="danger" type="button" data-credential-action="clear" data-i18n="credentialClear"></button></div><p class="inline-status" id="${id}-test-status"></p>`;
}

function capitalized(value: string): string {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
}
